### ISSUE TITLE
First `flox install` fails on macOS - can't stat `~/.local/share/flox/environments/local`

### ISSUE THREAD

**Issue by vtbassmatt** [flox/flox#16] opened 2023-03-26 12:47 UTC
I was following the tutorial at https://floxdev.com/docs/ with a fresh install of 0.1.2-r427-0.0.10-r216. When I tried to `flox install cowsay`, I got the following message:

```ShellSession
% flox install cowsay
Updating git config "/Users/vtbassmatt/.config/flox/gitconfig"
[> Do you consent to the collection of basic usage metrics? Yes
Thank you for helping to improve flox!
Did not find "/Users/vtbassmatt/.config/flox/floxUserMeta.json", continuing with
out user channels
Updating /Users/vtbassmatt/.config/flox/nix.conf
++++ /nix/store/ifh1jqp2yc2pgiaf7fqgi4qpz0q82iyp-flox-0.0.10-r216/libexec/flox/g
h repo create --private https://github.com/vtbassmatt/floxmeta --template https:
//github.com/flox/floxmeta-template.git
error: stating symlink '/Users/vtbassmatt/.local/share/flox/environments/local'
: No such file or directory
```

Sure enough, activating the environment and running `cowsay` didn't work. I tried the install again and it worked on the second run.

<img width="682" alt="flox-error" src="https://user-images.githubusercontent.com/714283/227776716-5b901314-deb6-4acf-8ab4-2727973d9262.png">

**Comment by ysndr** [comment] 2023-03-31 12:16
hej @vtbassmatt , I'm looking into this issue.

Can I assume that you have used `gh` before?

**Comment by vtbassmatt** [comment] 2023-03-31 14:22
Yes but possibly not on this computer.

**Comment by aakropotkin** [comment] 2023-04-10 18:23
Unfortunately we have been unable to reproduce this issue with our MacOS VMs.

Can you confirm that this issue still occurs on your machine with the latest version of `flox` ( Version: 0.1.3-r437-0.0.10-r219 )?

**Comment by vtbassmatt** [comment] 2023-04-10 20:03
Also, I'm fine with you closing this no-repro. I'm not the target market for Flox and was only kicking tires, so if you're not seeing the issue with other customers, then it likely doesn't matter whether it's "fixed" or not :)

**Comment by robinbrantley** [comment] 2023-04-25 19:48
going ahead and closing as we haven't been able to reproduce the bug.

**Closed by robinbrantley** 2023-04-25 19:48 UTC

**Comment by limeytexan** [comment] 2023-05-20 18:33
FTR, I believe this was fixed as part of the set of fixes merged with https://github.com/flox/flox-bash-private/pull/520. The essence of the problem was that we were treating the existence of paths in `~/.local/share/flox/environments/...` as an authoritative record of the environment, when in fact the source of truth was the `floxmeta` repository. That set of fixes changed that, and thus fixed this at the same time.
