### ISSUE TITLE
Document system requirements for flox CLI

### ISSUE THREAD

**Issue by stahnma** [flox/flox#860] opened 2024-01-25 02:15 UTC
**Describe the bug:**

We have no documentation about what the minimum requirements are for flox. 

**Steps to reproduce:**
1. Have a smol machine. 
2. Attempt to use flox. 
3. Just wait longer and maybe give up or lean into a nice oom-kill. 

Result: 

Smol boy no work. 

Expected: 

Tell me ahead of time smol boy won't work (or make it work). 

This is a quite small machine. (1 GB of RAM). I've also tried a 4GB of RAM machine. 

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

**Comment by ghudgins** [comment] 2024-01-25 02:18
duplicate of https://github.com/flox/flox/issues/839

**Comment by ghudgins** [comment] 2024-01-25 16:02
added AC to #839 and will track there

**Closed by ghudgins** 2024-01-25 16:02 UTC
Labels: bug
