### ISSUE TITLE
Unable to install cudatoolkit

### ISSUE THREAD

**Issue by stahnma** [flox/flox#679] opened 2023-12-20 04:23 UTC
**Describe the bug:**

I can't install cudatoolkit

**Steps to reproduce:**
1.  'flox search cuda` # Notice that cudatoolkit is a package
2. `flox install cudatoolkit` # Notice it fails
3.  File bug. 

Result: 
 ```
% flox init                                                                                 /tmp/tmp.Hqm00bALHH fedora
✨ Created environment tmp.Hqm00bALHH (x86_64-linux)

Next:
  $ flox search <package>    <- Search for a package
  $ flox install <package>   <- Install a package into an environment
  $ flox activate            <- Enter the environment

 % flox search cuda                                                                          /tmp/tmp.Hqm00bALHH fedora
vimPlugins.nvim-treesitter-parsers.cuda  <no description provided>
cudatext                                 Cross-platform code editor
cudatext-gtk                             Cross-platform code editor
cudatext-qt                              Cross-platform code editor
cudatoolkit                              A compiler for NVIDIA GPUs, math libraries, and tools
cudatoolkit_11                           A compiler for NVIDIA GPUs, math libraries, and tools
mathematica-cuda                         Wolfram Mathematica computational software system
tiny-cuda-nn                             Lightning fast C++/CUDA neural network framework
caffeWithCuda                            Deep learning framework
colmapWithCuda                           COLMAP - Structure-From-Motion and Multi-View Stereo pipeline

Showing 10 of 83 results. Use `flox search cuda --all` to see the full list.
Use `flox show <package>` to see available versions
 % flox install cudatoolkit                                                                  /tmp/tmp.Hqm00bALHH fedora
ERROR: error building environment:
 %

```

With `--debug`

```
 % flox install --debug cudatoolkit                                                          /tmp/tmp.Hqm00bALHH fedora
[DEBUG] [flox::config] `$FLOX_CONFIG_HOME` not set, using "/home/stahnma/.config/flox/"
[DEBUG] [flox::commands] Metrics collection disabled
[DEBUG] [flox::utils::init] no default user nix.conf found - weird
[DEBUG] [flox::utils::init::metrics] Attempting to read own UUID from file
[DEBUG] [flox::commands::environment] installing packages [cudatoolkit] to Unspecified
[DEBUG] [flox_rust_sdk::models::environment] looking for .flox: starting_path=/tmp/tmp.Hqm00bALHH/.flox
[DEBUG] [flox_rust_sdk::models::environment] .flox found: path=/tmp/tmp.Hqm00bALHH/.flox
[DEBUG] [flox::commands] detected concrete environment type: path
[DEBUG] [flox_rust_sdk::models::environment::path_environment] attempting to open .flox directory: /tmp/tmp.Hqm00bALHH/.flox
⠁ Installing packages to environment tmp.Hqm00bALHH at /tmp/tmp.Hqm00bALHH...                                           [DEBUG] [flox_rust_sdk::models::manifest] attempting to insert packages into manifest
[DEBUG] [flox_rust_sdk::models::manifest] package newly installed: id=cudatoolkit, path=cudatoolkit
⠁ Installing packages to environment tmp.Hqm00bALHH at /tmp/tmp.Hqm00bALHH...                                           [DEBUG] [flox_rust_sdk::models::environment::core_environment] transaction: making temporary environment in /home/stahnma/.cache/flox/process/.tmp0waJIE/.tmpmIScLb
[DEBUG] [flox_rust_sdk::models::environment::core_environment] transaction: updating manifest
[DEBUG] [flox_rust_sdk::models::environment::core_environment] writing new manifest to /home/stahnma/.cache/flox/process/.tmp0waJIE/.tmpmIScLb/manifest.toml
[DEBUG] [flox_rust_sdk::models::environment::core_environment] transaction: building environment
[DEBUG] [flox_rust_sdk::models::environment::core_environment] no existing lockfile found
[DEBUG] [flox_rust_sdk::models::environment] global manifest path is /home/stahnma/.config/flox/global-manifest.toml
[DEBUG] [flox_rust_sdk::models::environment::core_environment] locking manifest with command: "/nix/store/676hygvwdx2ckbc14nrlyaziwy8nxiws-flox-pkgdb-0.1.0/bin/pkgdb" "manifest" "lock" "--ga-registry" "--global-manifest" "/home/stahnma/.config/flox/global-manifest.toml" "--manifest" "/home/stahnma/.cache/flox/process/.tmp0waJIE/.tmpmIScLb/manifest.toml"
⠙ Installing packages to environment tmp.Hqm00bALHH at /tmp/tmp.Hqm00bALHH...                                           [DEBUG] [flox_rust_sdk::models::environment::core_environment] generated lockfile, writing to /home/stahnma/.cache/flox/process/.tmp0waJIE/.tmpmIScLb/manifest.lock
[DEBUG] [flox_rust_sdk::models::environment::core_environment] building environment: system=x86_64-linux, lockfilePath=/home/stahnma/.cache/flox/process/.tmp0waJIE/.tmpmIScLb/manifest.lock
[DEBUG] [flox_rust_sdk::models::environment::core_environment] building environment with command: "/nix/store/676hygvwdx2ckbc14nrlyaziwy8nxiws-flox-pkgdb-0.1.0/bin/pkgdb" "buildenv" "{\"lockfile-version\":0,\"manifest\":{\"install\":{\"cudatoolkit\":{\"path\":\"cudatoolkit\"}},\"registry\":{\"defaults\":{\"subtrees\":null},\"inputs\":{\"nixpkgs\":{\"from\":{\"owner\":\"NixOS\",\"ref\":\"release-23.05\",\"repo\":\"nixpkgs\",\"type\":\"github\"},\"subtrees\":[\"legacyPackages\"]}},\"priority\":[\"nixpkgs\"]}},\"packages\":{\"x86_64-linux\":{\"cudatoolkit\":{\"attr-path\":[\"legacyPackages\",\"x86_64-linux\",\"cudatoolkit\"],\"info\":{\"broken\":false,\"license\":null,\"pname\":\"cudatoolkit\",\"unfree\":true,\"version\":\"11.7.0\"},\"input\":{\"attrs\":{\"lastModified\":1702882221,\"narHash\":\"sha256-L/uOrBqkGsa45EvQk4DLq/aR6JeomW+7Mwe0mC/dVUM=\",\"owner\":\"NixOS\",\"repo\":\"nixpkgs\",\"rev\":\"25fef6e30d8ad48f47a8411ccfe986d8baed8a15\",\"type\":\"github\"},\"fingerprint\":\"0bba17e4e0d149b3e3612d69653fa6970af2e167f228b939168c9ae65f320cf7\",\"url\":\"github:NixOS/nixpkgs/25fef6e30d8ad48f47a8411ccfe986d8baed8a15\"},\"priority\":5}}},\"registry\":{\"defaults\":{\"subtrees\":null},\"inputs\":{\"nixpkgs\":{\"from\":{\"lastModified\":1702882221,\"narHash\":\"sha256-L/uOrBqkGsa45EvQk4DLq/aR6JeomW+7Mwe0mC/dVUM=\",\"owner\":\"NixOS\",\"repo\":\"nixpkgs\",\"rev\":\"25fef6e30d8ad48f47a8411ccfe986d8baed8a15\",\"type\":\"github\"},\"subtrees\":[\"legacyPackages\"]}},\"priority\":[\"nixpkgs\"]}}"
[ERROR] [flox] error building environment:
 %
```

Expected: 

I have cudatoolkit installed into the environment, or helpful error messages. 

📓  FWIW, `cudaPackages.cudatoolkit` also has the same error. 

**Screenshots/terminal output (if relevant):**

** flox Version (run `flox --version` if possible): **

Version: 0.3.6-168-g2d8d41c
![Cursor_and_stahnma_fedora__tmp_tmp_Hqm00bALHH_and_New_Issue_·_flox_flox](https://github.com/flox/flox/assets/6961/a2adbebb-f553-47b3-a861-c1f32e540e37)

**Comment by ysndr** [comment] 2023-12-20 16:40
the error message should also now be handled with #672

The error will say, that cuda is a nonfree package, so the work revolving that will likely fix this

**Comment by mkenigs** [comment] 2023-12-20 17:42
The error now prints as:
```
> flox install cudatoolkit
ERROR: error building environment: caught a nix exception: running pkgdb subcommand: error:
           … in the condition of the assert statement

             at /nix/store/5mac6jk45rx1mvyknhw2dyhykgjbkx6a-source/lib/customisation.nix:229:17:

              228|       drvPath = assert condition; drv.drvPath;
              229|       outPath = assert condition; drv.outPath;
                 |                 ^
              230|     };

           … while evaluating the attribute 'handled'

             at /nix/store/5mac6jk45rx1mvyknhw2dyhykgjbkx6a-source/pkgs/stdenv/generic/check-meta.nix:447:7:

              446|       # or, alternatively, just output a warning message.
              447|       handled =
                 |       ^
              448|         {

           (stack trace truncated; use '--show-trace' to show the full trace)

           error: Package ‘cudatoolkit-11.7.0’ in /nix/store/5mac6jk45rx1mvyknhw2dyhykgjbkx6a-source/pkgs/development/compilers/cudatoolkit/common.nix:334 has an unfree license (‘unfree’), refusing to evaluate.

           a) To temporarily allow unfree packages, you can use an environment variable
              for a single invocation of the nix tools.

                $ export NIXPKGS_ALLOW_UNFREE=1

            Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
            (Flake) command, `--impure` must be passed in order to read this
            environment variable.

           b) For `nixos-rebuild` you can set
             { nixpkgs.config.allowUnfree = true; }
           in configuration.nix to override this.

           Alternatively you can configure a predicate to allow specific packages:
             { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
                 "cudatoolkit"
               ];
             }

           c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
             { allowUnfree = true; }
           to ~/.config/nixpkgs/config.nix.
```

**Comment by mkenigs** [comment] 2023-12-20 17:42
Duplicate of https://github.com/flox/flox/issues/492

**Comment by ghudgins** [comment] 2023-12-20 17:42
duplicate of https://github.com/flox/flox/issues/492

**Closed** 2023-12-20 17:42 UTC
Labels: bug, team-cli

**Comment by stahnma** [comment] 2023-12-20 17:44
Part of it is duplicate. The part where the error is completely unhelpful is also part of the issue. (and that I still can't install cudatoolkit is an issue)

**Comment by mkenigs** [comment] 2023-12-20 17:59
#492 says we need to clean up the error, so I'm not sure which part is not duplicate?

**Comment by samrose** [comment] 2024-01-29 14:05
I was able to install cuda toolkit via nix and get PyTorch installed via pip in a nix Dev env working on  Ubuntu based Linux so long as nvidia driver was already installed via OS pkg

if one of you are working on this, ping me and I can share what I learned.  Everything from nix implementation probably translates to flox.
