### ISSUE TITLE
Separate user shell initialization and generic environment initialization

### ISSUE THREAD

**Issue by rossturk** [flox/flox#1019] opened 2024-02-15 03:19 UTC
## Motivation

**When** I am setting up the environment
**I need** access to a script that works regardless of the shell (for initialization, dominantly),
**And** a script that sets aliases and environment variables that will run for all shells,
**And** a script that does shell-specific initialization,
**So I can** have consistency across environments without losing access to shell aliases. 

## Acceptance Criteria

Checklist:
- [x] Add new fields to the manifest
- [x] Remove the `hook.file` option
- [x] Update the manifest template
- [ ] Edit the docs to reflect the new manifest fields
- [x] Handle activation of the new fields
- [x] Add tests for the new fields

_Change the manifest template (add `[profile]` and add `hook.on-activate`)_

**When** I `flox init` in a clean directory
**And** I `flox edit`
**Then** I see ...
```
...

# A profile script is sourced by your shell when entering the environment.
# The `profile.common` script is sourced by all shells.
# The `profile.<shell>` scripts are sourced after `profile.common`,
# and are only sourced by the specified shell.
# This allows you to perform both generic and shell-specific initialization.
# A common use case is dynamically setting environment variables and setting
# shell aliases.

[profile]
# common = """
#     alias gp="git pull"
#     export FOO="BAR"
# """
#
# bash = """
#     export SPECIFIC="baz"
# """
# 
# zsh = """
#     export SPECIFIC="qux"
# """


# The `hook.on-activate` script is executed in a `bash` shell after the profile
# scripts have been sourced.
# This means that any environment variables you set in your profile scripts
# will be available to the `hook.on-activate` script.
#
# This script is useful for performing more involved initialization in a
# consistent shell enviroment.

[hook]
# on-activate = """
#     echo "it's gettin flox in here"
# """
```

_Hook scripts always run in bash_

**Given** I am a zsh user (MacOS)
**And** I have `flox init` a fresh environment
**When** I customize the `on-activate` field with this script

```
[hook]
on-activate = """
        echo "-- testing behavior"
        echo "array[1] in zsh is the first element (foo); in bash it's the second (bar)"
        test_array=("foo" "bar" "baz")
        echo "it is: ${test_array[1]}"
"""
```
**And** I `flox activate`
**Then** I see 'bar'

_Common profile script is sourced before shell-specific profile script_

**Given** I am a user of `<shell>`
**When** I have the following `profile.common` script

```
common = """
    export greeting="hello"
"""
```

**And** I have the following `profile.<shell>` script

```
<shell> = """
    echo "$greeting"
"""
```

**When** I run `flox activate`
**Then** I see `hello`.

_The `hook.on-activate` script is run in a bash subshell after the user's shell has sourced the profile scripts_

**Given** I am a user of `<shell>`
**And** I have the following `profile.common` script

```
common = """
    export greeting="hello"
"""
```

**And** I have the following `hook.on-activate` script

```
on-activate = """
    echo "$greeting"
    export greeting="aloha"
"""
```

**When** I run `flox activate`
**Then** I see `hello`
**And** When I run `echo "$greeting"`
**Then** I see `hello`

_Deprecation message_

@ghudgins to fill in
migration: continue to support the old field. print a deprecation message. update the template

## Original bug

**Describe the bug:**

Authors need to be able to write shell hooks with an expectation of which shell they'll be run in. I thought this was `bash` consistently, but it seems to be variable depending on something in the parent environment.

**Steps to reproduce:**
Create a manifest with these contents:
```
[install]

[hook]
script = """
        echo
        echo "-- environment"
        echo "BASH_VERSINFO: $BASH_VERSINFO"
        echo "ZSH_VERSION: $ZSH_VERSION"
        echo

        psline=$(ps -o command "$$")
        echo "-- ps line:"
        echo $psline
        echo

        echo "-- testing behavior"
        echo "array[1] in zsh is the first element (foo); in bash it's the second (bar)"
        test_array=("foo" "bar" "baz")
        echo "it is: ${test_array[1]}"
"""

[options]
systems = ["aarch64-darwin", "x86_64-linux"]
```

On a system where my user's shell was `bash`, my output was:
```
rturk@flox1:/tmp/tmp.IgJ4kB6rIH$ echo $SHELL
/bin/bash

rturk@flox1:/tmp/tmp.IgJ4kB6rIH$ flox activate
✅  You are now using the environment tmp.IgJ4kB6rIH at /tmp/tmp.IgJ4kB6rIH.
To stop using this environment, type 'exit'

-- environment
BASH_VERSINFO: 5
ZSH_VERSION:

-- ps line:
COMMAND /bin/bash --rcfile /tmp/tmp.IgJ4kB6rIH/.flox/run/x86_64-linux.tmp.IgJ4kB6rIH/activate/bash

-- testing behavior
array[1] on zsh is the first element (foo), but on bash it's the second (bar)
it is: bar
```

On a system where my user's shell was `zsh`, the output was:
```
tmp.98bKiUkGtM % echo $SHELL
/bin/zsh

tmp.98bKiUkGtM % flox activate
✅ You are now using the environment tmp.98bKiUkGtM at /private/var/folders/80/1mw7plyj62vgbkq2_df32n640000gn/T/tmp.98bKiUkGtM.
To stop using this environment, type 'exit'

-- environment
BASH_VERSINFO:
ZSH_VERSION: 5.9

-- ps line:
COMMAND
/bin/zsh --no_globalrcs

-- testing behavior
array[1] on zsh is the first element (foo), but on bash it's the second (bar)
it is: foo
flox [tmp.98bKiUkGtM] tmp.98bKiUkGtM %
```

**Comment by mkenigs** [comment] 2024-02-15 15:33
Some steps of activation have to be run in the shell being activated, e.g. aliases. Some steps could always be run in e.g. bash, but if we put the shell hook in bash, then it has to be run before we set aliases, and it prevents users from doing some things like setting aliases. Currently `SHELL` is respected, so you can set that if you need to. Or if it was really important to enforce consistency, we could add a setting like `options.shell = "bash"`

**Comment by rossturk** [comment] 2024-02-15 20:07
I think it's pretty important that shell hooks execute consistently across environments without requiring any special steps on the part of the author.

Say, for example, a user defines a shell hook that would pull secrets from an array: one for each deployment across dev/test/prod. They write their hook in `bash` on Linux. They activate their environment with the intention of deploying new code, but they activate on macOS so it runs with `zsh`. The hook might pull a different set of secrets from the array and potentially deploy our user's work to the wrong spot, given how zsh and bash deal with array indexes differently. If they happen to share it with someone who uses `tcsh`, the entire hook is likely to fail.

We can respect `SHELL` or offer a `options.shell`, but doing so puts the responsibility on the **author** to take explicit steps to ensure consistency. If the author fails to take those steps, their environment will behave unpredictably - and possibly fail in ways that are not immediately noticeable to the user.

Unless we insert this new required configuration into the manifest template, or add it for them on init, authors will generally not know to do it; I can't think of a good reason why someone would *want* to author a shell hook in anything but bash, so I'm not sure how far I'd want to go to teach them.

**Comment by rossturk** [comment] 2024-02-15 20:22
(Another small consideration: if we allow authors to declare the hook's shell in `options.shell` we probably need to make sure that shell exists on a user's machine upon activation.)

**Comment by mkenigs** [comment] 2024-02-15 20:25
> I can't think of a good reason why someone would _want_ to author a shell hook in anything but bash, so I'm not sure how far I'd want to go to teach them.

- If I want to add aliases in my hook, I'd need it to respect SHELL. I think aliases will be pretty common. Needing to add them in the hook is less common, but still something to keep in mind.
- If I want the hook to respect SHELL's rc files, we'd need to respect SHELL. I'm not sure how common that will be

I think you're right that sometimes it would be nice to know what shell you're using. Some options:
- drop support for SHELL, which breaks the use cases I just mentioned
- add multiple kinds of hooks, e.g. `hook.bash`, `hook.SHELL`
- add `options.shell`
- recommend `[install] bash = {}` and `bash ../script.sh`

**Comment by mkenigs** [comment] 2024-02-15 20:25
> (Another small consideration: if we allow authors to declare the hook's shell in `options.shell` we probably need to make sure that shell exists on a user's machine upon activation.)

I would think if we do that, we'd probably use a Nix provided shell

**Comment by ghudgins** [comment] 2024-02-15 20:56
I think we lose some of the magic if we hit people in the face with another `options` by default. to wave a wand here I would rather we just assume the lack of some option means a bash shell and we provide options for those who want something different. I know that means it's not as declarative as it could be but as long as we don't mess around with that behavior too much I think it'll be okay (and for the people who want to declare they can still declare). Flox has an opportunity to be the _sensible default_ product instead of the ultimate customization product and I think that fits our goals a bit better.

**Comment by mkenigs** [comment] 2024-02-15 21:07
Okay so just to be clear, that means you want two phase activation?
```
bash -c "./path/to/hook; $SHELL --rcfile ./path/to/activate"
```
And the order of activation would be:
- Shell hook
- RC files
- Prompt
- Env vars
- Aliases

So shell hook doesn't have access to RC files, env vars, or aliases. Or if you want we could do:
- Env vars
- Aliases
- Shell hook
- RC files
- Prompt
- Aliases again

**Comment by ghudgins** [comment] 2024-02-15 21:33
maybe a quick call would be best but i'll try to clarify here. of the solutions you listed here's what I feel is the best one and why:

 - don't change the manifest for most people. users don't need to worry about this most of the time. let's assume the lack of an option means a specific behavior that we can document. that behavior produces consistency across most systems
 - because, to fix the above, we have to make some choices. we expose those in the manifest as optional options just for people who want a very specific behavior that's different than the sensible default we chose. 
 - we don't lose aliases in the process. 

I do think we should resolve this so people don't get lost trying to figure out why editing their manifest in an IDE (and assuming bash) doesn't quite work that way when Flox is non-deterministically using whatever shell my system is.

**Comment by aakropotkin** [comment] 2024-02-16 02:18
Its really important for our hooks to be POSIX compliant for the reasons this ticket has raised.

**Comment by ysndr** [comment] 2024-02-19 12:59
zsh, by default, is _not_ posix compliant. 
It tries to _emulate_ `sh` if invoked as `sh` or `ksh` but otherwise does not guarantee compliance (we ran into this before with `eval <(prog)` which gets you locked up in zsh in certain situations).
This issue isn't really about our hooks though (I dont disagree that our shell scripts should be compliant!).
The problem is that as a flox user you have double duty to make sure your script is compatible on all systems you run the env on.
Though you always have to if you support different systems like you have to set `install.<pid>.[systems|optional]` for certain packages and make sure you don't refer to `/usr/bin/only-there-on-macos`.

**Comment by nicklewis** [comment] 2024-02-20 20:28
We're running into an example of this issue for floxEM development. Specifically, we run 
`eval "<(nix print-dev-env ...)"`, which doesn't work on zsh. The problem is exacerbated in our case because there _is_ no valid zsh code we could run instead.

https://github.com/flox/floxEM/blob/main/.flox/env/manifest.toml#L52

**Comment by ghudgins** [comment] 2024-02-20 22:00
Spoke with @mkenigs - we like this proposal the best:

* we change `hook.script` so it always executes in bash. this would be a breaking change but I'm okay with it as I think it's what most people expect (and there's a way to restore the previous functionality very simply).
* we introduce `hook.rc` - runs in the shell.

**Comment by limeytexan** [comment] 2024-02-22 17:02
> we change hook.script so it always executes in bash

+1 ... would just add this should be the Nix-provided bash (not sure that should be bash or bashInteractive).

> we introduce hook.rc - runs in the shell

It's possible I don't understand the suggestion, but I don't know how it would be possible to write that "hook.rc" logic in one language and have it activate identically across multiple shells (including non-posix-compliant shells like tcsh, fish). I don't know how any one "hook" could be made to do that.

In my view the problem breaks down to the following phases:

1. *preparation*: as we prepare for activation the flox CLI is able to perform actions (create files, etc.) to "set the stage" for the subsequent activation, which notably includes a) setting of environment variables (e.g. `FLOX_ENV`) and b) creating files and scripts required for later stages of the activation.
2. *exec() bash <script>*: the next stage of processing is to `exec()` the flox-provided Nix bash to perform further processing, which takes the form of a script including the user-specified [bash] hook along with further flox-specified post processing.
3. *exec() `$SHELL`*: at the conclusion of the user-specified hook processing, it's essential that we `exec()` into the user's own `$SHELL`, but in a way that doesn't break all of the customization performed in steps 1 & 2 (particularly the setting of `$PATH`). This can take the form of invoking the shell with _"rc"-related_ options which a) prevent the processing of user-specific "dotfiles" (which will often perturb the value of `$PATH`) and b) invoke a flox-provided, language-specific script for the setting of shell-specific functionality (like aliases, see below).
4. *set aliases*: as mentioned above, the flox-provided shell "rc" invocation script provides us the opportunity to invoke configuration statements that differ by `$SHELL` language. One notable example of which is the setting of aliases, which requires a different command in each of posix, tcsh, and fish. If the flox CLI can accurately guess the user's shell [language] from `$SHELL` then it can conclude the activation [bash] script with an `exec $SHELL --rc /path/to/rc` _equivalent_ invocation that can then perform language-specific configuration, including the setting of aliases.
    * Notably this requires that aliases be declared as distinct from the activation hook, as was previously the case.

**Comment by zmitchell** [comment] 2024-03-07 21:39
Adding the `hook.on-activate` script and removing the `hook.file` field is done. We have docs and tests for the new field. The next PR will finish out this ticket by adding the `profile.*` section of the manifest (including tests and docs). A separate ticket will address detecting and warning about the deprecated `hook.script` field.

**Comment by ghudgins** [comment] 2024-03-20 21:15
@zmitchell @billlevine when should I expect doc for this?

**Comment by billlevine** [comment] 2024-03-21 16:35
> @zmitchell @billlevine when should I expect doc for this?

The last PR included man page updates for this.  Is there something else missing?

**Comment by zmitchell** [comment] 2024-03-21 16:36
Floxdocs

**Comment by ghudgins** [comment] 2024-03-21 17:29
did the PR include `man manifest.toml` changes? maybe i'm not running what I thought I was...

**Comment by billlevine** [comment] 2024-03-21 18:02
It did. https://github.com/flox/flox/pull/1149/files#diff-da582d3a151d3d334a3bb730633a88a8ad37b7c23ff12918859eab3891afaa91

**Comment by ghudgins** [comment] 2024-03-22 14:23
ah I see it now. just needs this heading section added

<img width="435" alt="image" src="https://github.com/flox/flox/assets/5465514/e2e8ddee-0552-4ecb-96ab-f05bb1dfe97b">

**Comment by ghudgins** [comment] 2024-03-22 14:24
otherwise this change LGTM and can close when we have the doc tasks accounted for

**Comment by ghudgins** [comment] 2024-03-22 22:03
well done all! closing

**Closed by ghudgins** 2024-03-22 22:03 UTC
Labels: bug, team-cli, product
