### ISSUE TITLE
Darwin `/usr/libexec/path_helper` rearranges PATH provided by `flox activate`

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#811] opened 2024-01-19 15:37 UTC
**Describe the bug:**

It's currently not possible to `eval "$(flox activate)"` from within any of `.{zlogin,zprofile,zshenv,zshrc}` files on Darwin without `/usr/libexec/path_helper -s` reordering the PATH to put the flox-provided environments _last_, after all the apple-provided stuff.

This is not new, we identified and fixed this with the previous version of flox using the [darwin-path-fixer.awk](https://github.com/flox/flox-bash/blob/main/libexec/flox/darwin-path-fixer.awk) script as invoked from [activate.sh](https://github.com/flox/flox-bash/blob/main/lib/commands/activate.sh#L239). 

**Steps to reproduce:**
1. on Darwin, use `zsh` as your default shell
2. add `eval "$(flox activate)"` to any of your `.{zlogin,zprofile,zshenv,zshrc}` files
3. start a new shell
4. `echo $PATH` and observe all the flox-provided environments have been moved to the end
    1. and if they haven't, invoke `tmux` (which invokes a new login shell for each new pane) and repeat

I'll note that the previous solution does still work, and I find that copying a slightly-modified version of the awk script from the old flox and sourcing it from within my `.zprofile` reliably fixes it for me:
```
export PATH=$(echo $PATH | awk -v shellDialect=bash -f ~/darwin-path-fixer.awk)
```

Attaching a copy of the modified awk script to this issue: [darwin-path-fixer.awk](https://github.com/flox/flox/files/13991182/darwin-path-fixer.awk.txt)

**flox Version (run `flox --version` if possible):**

```
flox [default] brantley@Michaels-MacBook-Pro ~ % flox --version
Version: 0.3.6-244-g7777245
```

**Comment by ghudgins** [comment] 2024-01-22 22:44
I can repro. initially (before tmux) - 

```
/Users/ghudgins/.flox/run/aarch64-darwin.default/bin:/Users/ghudgins/.flox/run/aarch64-darwin.default/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ghudgins/.yarn/bin:/Users/ghudgins/.config/yarn/global/node_modules/.bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/ghudgins/.local/bin:/Users/ghudgins/.nvm/versions/node/v16.19.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.s
```

after tmux
```
/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ghudgins/.yarn/bin:/Users/ghudgins/.config/yarn/global/node_modules/.bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/ghudgins/.local/bin:/Users/ghudgins/.nvm/versions/node/v16.19.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/ghudgins/.flox/run/aarch64-darwin.default/bin:/Users/ghudgins/.flox/run/aarch64-darwin.default/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ghudgins/.yarn/bin:/Users/ghudgins/.config/yarn/global/node_modules/.bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/ghudgins/.local/bin:/Users/ghudgins/
```

**Comment by limeytexan** [comment] 2024-01-25 17:18
I did some empirical observation today, observing the effects of running `flox activate` from each of the `.{zprofile,zlogin,zshrc,zshenv}` files in turn (all 16 combinations), and recording the effects of each of these with regard to these four behaviours:

1. *PS1*: whether the prompt was configured appropriately
2. *PATH*: whether the `PATH` was updated to include the flox environment
3. *order*: whether the `PATH` was ordered correctly with the flox environment `{s,}bin` directories first
4. *activate*: whether the `ERROR: Environment 'limeytexan/default at /Users/brantley' is already active` message was displayed

... and in these [3] contexts:

1. *login*: when first starting a login shell (e.g. by hitting `<command>-<n>` from the Mac Terminal App)
2. *tmux*: by invoking `tmux` from within the login shell (notably this will start a second nested login shell)
3. *shell*: by invoking a non-login shell and inspecting the resulting `PATH` with `ssh localhost 'echo $PATH'`

In each case I've recorded a checkmark to reflect "good", and a red X for "bad". 

| .zprofile | .zlogin | .zshrc | .zshenv |   | PS1 | PATH | order | activate |   | PS1 | PATH | order | activate |   | PATH | order | activate |
| :-------: | :-----: | :----: | :-----: | - | :-: | :--: | :---: | :------: | - | :-: | :--: | :---: | :------: | - | :--: | :---: | :------: |
|           |         |        |         |   | login | ----> | ----> | ----> |   | tmux  | ----> | ----> | ----> |   | shell | ----> | ----> |
|   |   |   |   || :x: | :x: | :x: | :heavy_check_mark: || :x: | :x: | :x: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
|   |   |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
|   |   | :ballot_box_with_check: |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
|   |   | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
|   | :ballot_box_with_check: |   |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
|   | :ballot_box_with_check: |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
|   | :ballot_box_with_check: | :ballot_box_with_check: |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
|   | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: |   |   |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: |   |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: |   | :ballot_box_with_check: |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: |   | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: |   |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

As you can see, there is no combination for which `flox activate` works across the board in all the required contexts. As near as I can tell this boils down to three behaviours:

1. `/usr/libexec/path_helper` re-ordering of `PATH`: as mentioned in the top of this issue, Apple is messing up the `PATH` as configured by `flox activate`
2. failing to perform mandatory subshell start-up: as indicated by the "already active" warning `flox` doesn't consistently source the startup logic to set `PS1` (and re-order the `PATH` to fix damage imposed by the `/usr/libexec/path_helper`)
3. spurious warnings: the above experiment confirms there is no one `.z*` file that will work both in a login and non-login shell, which confirms zsh users (on Mac) are likely going to need to invoke `flox activate` from both their `.zshenv` and one of `.{zlogin,zprofile}` in order to get consistent activation in all contexts. This requirement suggests that flox activate will need to be run twice for a login shell, so we need to avoid throwing a warning in that case.

**Comment by limeytexan** [comment] 2024-01-25 17:18
I did some empirical observation today, observing the effects of running `flox activate` from each of the `.{zprofile,zlogin,zshrc,zshenv}` files in turn (all 16 combinations), and recording the effects of each of these with regard to these four behaviours:

1. *PS1*: whether the prompt was configured appropriately
2. *PATH*: whether the `PATH` was updated to include the flox environment
3. *order*: whether the `PATH` was ordered correctly with the flox environment `{s,}bin` directories first
4. *activate*: whether the `ERROR: Environment 'limeytexan/default at /Users/brantley' is already active` message was displayed

... and in these [3] contexts:

1. *login*: when first starting a login shell (e.g. by hitting `<command>-<n>` from the Mac Terminal App)
2. *tmux*: by invoking `tmux` from within the login shell (notably this will start a second nested login shell)
3. *shell*: by invoking a non-login shell and inspecting the resulting `PATH` with `ssh localhost 'echo $PATH'`

In each case I've recorded a checkmark to reflect "good", and a red X for "bad". 

| .zprofile | .zlogin | .zshrc | .zshenv |   | PS1 | PATH | order | activate |   | PS1 | PATH | order | activate |   | PATH | order | activate |
| :-------: | :-----: | :----: | :-----: | - | :-: | :--: | :---: | :------: | - | :-: | :--: | :---: | :------: | - | :--: | :---: | :------: |
|           |         |        |         |   | login | ----> | ----> | ----> |   | tmux  | ----> | ----> | ----> |   | shell | ----> | ----> |
|   |   |   |   || :x: | :x: | :x: | :heavy_check_mark: || :x: | :x: | :x: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
|   |   |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
|   |   | :ballot_box_with_check: |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
|   |   | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
|   | :ballot_box_with_check: |   |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
|   | :ballot_box_with_check: |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
|   | :ballot_box_with_check: | :ballot_box_with_check: |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
|   | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: |   |   |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: |   |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: |   | :ballot_box_with_check: |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: |   | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: |   |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :x: | :heavy_check_mark: |
| :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :x: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

As you can see, there is no combination for which `flox activate` works across the board in all the required contexts. As near as I can tell this boils down to three behaviours:

1. `/usr/libexec/path_helper` re-ordering of `PATH`: as mentioned in the top of this issue, Apple is messing up the `PATH` as configured by `flox activate`
2. failing to perform mandatory subshell start-up: as indicated by the "already active" warning `flox` doesn't consistently source the startup logic to set `PS1` (and re-order the `PATH` to fix damage imposed by the `/usr/libexec/path_helper`)
3. spurious warnings: the above experiment confirms there is no one `.z*` file that will work both in a login and non-login shell, which confirms zsh users (on Mac) are likely going to need to invoke `flox activate` from both their `.zshenv` and one of `.{zlogin,zprofile}` in order to get consistent activation in all contexts. This requirement suggests that flox activate will need to be run twice for a login shell, so we need to avoid throwing a warning in that case.

**Comment by ysndr** [comment] 2024-02-05 11:49
@limeytexan  since #868 #889 got merged now, we should redo your experiment (and set up an end2end test the catch regressions on this - though we need to know what we expect first)

**Comment by limeytexan** [comment] 2024-02-14 09:36
Thanks @ysndr for highlighting; lost this in my overflowing inbox and hope to circle back to redo the analysis soon.

**Comment by limeytexan** [comment] 2024-02-18 21:10
@ysndr sorry for the delay. I re-did the analysis and while things are better there still is no combination of activations that works in all cases.

In addition we've now got two new [order-related] issues that we didn't see before:
1. :heavy_exclamation_mark: both: flox env directories appear at both ends of the `PATH`
2. :bangbang: twice: flox env directories appear twice at the beginning of the `PATH`

The updated table is shown below. The "6" case (activating in .zlogin and .zshenv) seems to be pretty close; maybe that's a good place to start?

|   | .zprofile | .zlogin | .zshrc | .zshenv |   | PS1 | PATH | order | activate |   | PS1 | PATH | order | activate |   | PATH | order | activate |
| :-: | :-------: | :-----: | :----: | :-----: | - | :-: | :--: | :---: | :------: | - | :-: | :--: | :---: | :------: | - | :--: | :---: | :------: |
|   |           |         |        |         |   | login | ----> | ----> | ----> |   | tmux  | ----> | ----> | ----> |   | shell | ----> | ----> |
| 1 |   |   |   |   || :x: | :x: | :x: | :heavy_check_mark: || :x: | :x: | :x: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 2 |   |   |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :x: | :heavy_check_mark: || :x: | :heavy_check_mark: | :x: | :x: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| 3 |   |   | :ballot_box_with_check: |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 4 |   |   | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :heavy_check_mark: | :x: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| 5 |   | :ballot_box_with_check: |   |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 6 |   | :ballot_box_with_check: |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| 7 |   | :ballot_box_with_check: | :ballot_box_with_check: |   || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 8 |   | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| 9 | :ballot_box_with_check: |   |   |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :heavy_exclamation_mark: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 10 | :ballot_box_with_check: |   |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| 11 | :ballot_box_with_check: |   | :ballot_box_with_check: |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :bangbang: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 12 | :ballot_box_with_check: |   | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| 13 | :ballot_box_with_check: | :ballot_box_with_check: |   |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :bangbang: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 14 | :ballot_box_with_check: | :ballot_box_with_check: |   | :ballot_box_with_check: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| 15 | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: |   || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :bangbang: | :heavy_check_mark: || :x: | :x: | :heavy_check_mark: |
| 16 | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: || :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

Hope this helps ...

**Comment by mkenigs** [comment] 2024-03-15 23:06
I'm not seeing the original reproducer anymore, so I opened https://github.com/flox/flox/issues/1185 for followup, but I'm going to close this one

**Closed by mkenigs** 2024-03-15 23:06 UTC
Labels: bug, team-cli
