### ISSUE TITLE
Transactions fail if project is on a different file system/mount point

### ISSUE THREAD

**Issue by ysndr** [flox/flox#468] opened 2023-11-22 11:01 UTC
`fs::rename` requires both source and destination paths to be on the same file system. Since the project may be on any mount point on the system, it can not be guaranteed that restoring the .flox copy under transaction by renaming will succeed.

```
flox install hello
ERROR: Failed to move modified environment into place
    
    Caused by:
        Cross-device link (os error 18)
```

**Comment by mkenigs** [comment] 2023-11-22 15:49
Duplicate of https://github.com/flox/flox/issues/231

**Closed** 2023-11-22 15:50 UTC
Labels: bug, team-cli
