### ISSUE TITLE
could not read 'gh' config file error

### ISSUE THREAD

**Issue by yonidavidson** [flox/flox#44] opened 2023-05-17 07:57 UTC
I installed flox over an old version I had.
when running flox init/install etc I get that error:
![image](https://github.com/flox/flox/assets/5472778/d9fb5607-878d-42cf-a1b9-d25149f7d767)

**Comment by mkenigs** [comment] 2023-05-17 12:44
We're parsing `~/.config/gh/hosts.yml` and treating `oauth_token` as mandatory - we need to get a fix in for that! This is a duplicate of https://github.com/flox/flox/issues/22

**Comment by aakropotkin** [comment] 2023-05-17 15:14
Thanks for your report, we'll keep you posted as fixes progress.

**Closed** 2023-05-26 16:36 UTC
