### ISSUE TITLE
Add `disable_update_check` config option

### ISSUE THREAD

**Issue by stealthybox** [flox/flox#1935] opened 2024-08-13 16:56 UTC
It should be possible to disable the CLI update check.
It's a great default to leave enabled since our timers should make the check infrequent, and users often forget to update.
However, it's important we allow users to disable this check behavior for performance, agency, and security.

We'll support a new config option:
```
flox config set-bool disable_update_check true
```

**Comment by ghudgins** [comment] 2024-09-25 18:07
duplicate of #1308

**Closed by ghudgins** 2024-09-25 18:07 UTC
Labels: enhancement, team-cli
