### ISSUE TITLE
Fix flakey expect tests or find a better way to test code paths with dialogs

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1138] opened 2024-03-07 20:43 UTC
Expect tests are continuing to flake:
https://github.com/flox/flox/actions/runs/8193573406/job/22407612057?pr=1131#step:6:356
https://github.com/flox/flox/actions/runs/8193738916/job/22408165476?pr=1133#step:6:325
https://github.com/flox/flox/actions/runs/8195191518/job/22412890966#step:6:328

We either need to:
- ensure our expect tests are more reliable
- find a better way to test code paths that have dialogs without using expect. This would probably be faster and more reliable

AC:
Either:
- fix expect tests
- port all expect tests to some more reliable format

**Comment by ysndr** [comment] 2024-03-18 14:31
1 and 2 should be fixed with https://github.com/flox/flox/pull/1143.
They are a regression from adding spinners afaict.
3 is due to an exceptionally slow runner instance.

**Closed** 2024-04-08 19:01 UTC
Labels: team-cli
