### ISSUE TITLE
flox install no environment error messaging improvement

### ISSUE THREAD

**Issue by stahnma** [flox/flox#450] opened 2023-11-17 21:54 UTC
```
[0] stahnma@floxbox01 ~/goldiflox [demo] № flox install nodejs gnumake openssl
ERROR: No environment found in "./"

    Caused by:
        EnvNotFound
ERROR: Error adding metric: task was cancelled
```

I would expect a suggestion to init. 

I also would like to not see a metric error. 

**flox version 0.3.7-r743**

**Comment by ghudgins** [comment] 2023-11-17 22:08
duplicate of https://github.com/flox/flox/issues/440

**Closed by ghudgins** 2023-11-17 22:08 UTC
Labels: product
