### ISSUE TITLE
macOS Apple Silicon M1/M2/M3/M4: failed to install v1.3.3 via pkg or brew

### ISSUE THREAD

**Issue by qdrddr** [flox/flox#2299] opened 2024-10-30 16:03 UTC
**Describe the bug:**

**Steps to reproduce PKG:**
1. Downloaded pkg v1.3.3 from the website
2. Click install
3. Get failed to install message

**Steps to reproduce brew:**
1. `brew install flox`
2. Failure while executing

```shell
brew install flox                          
==> Downloading https://formulae.brew.sh/api/formula.jws.json
########################################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
########################################################################################################################################################################################################### 100.0%
==> Downloading https://downloads.flox.dev/by-env/stable/osx/flox-1.3.3.aarch64-darwin.pkg
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/4559bc557260a2ee6bb8c11efec639023690b13beaf6a5653ae1503a0c6791a1--flox-1.3.3.aarch64-darwin.pkg
==> Installing Cask flox
==> Running installer for flox with sudo; the password may be necessary.
Password:
installer: Package name is Flox
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “flox-1.3.3.aarch64-darwin.pkg”.)
==> Purging files for version 1.3.3 of Cask flox
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=user USER=user USERNAME=user -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/flox/1.3.3/flox-1.3.3.aarch64-darwin.pkg -target /` exited with 1. Here's the output:
installer: Package name is Flox
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “flox-1.3.3.aarch64-darwin.pkg”.)
```

Result:
Could not install the app

Expected:
Be able to install flox

**Screenshots/terminal output (if relevant):**

**Flox Version (run `flox --version` if possible):**

**`uname -a` output:**
Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000 arm64

![Image](https://github.com/user-attachments/assets/d6477b31-3e0f-4d7a-8c46-2866c5e4d6f8)

**Comment by mkenigs** [comment] 2024-10-30 16:23
Could you attach any logs for the install from `/var/log/install.log`? I'm looking at successful logs, but if you attach everything from the first mention of `com.floxdev.flox` to the last mention hopefully that will be what we need

**Comment by osteinhauer** [comment] 2024-11-12 14:29
```
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + '[' '~~> Setting up the build user _nixbld5' = '' ']'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo '~~> Setting up the build user _nixbld5'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ~~> Setting up the build user _nixbld5
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo -en '\033[0m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + poly_user_exists _nixbld5
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + /usr/bin/dscl . -read /Users/_nixbld5
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ poly_user_id_get _nixbld5
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ dsclattr /Users/_nixbld5 UniqueID
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ /usr/bin/dscl . -read /Users/_nixbld5
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ /usr/bin/awk '/UniqueID/ { print $2 }'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + actual_uid=305
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + '[' 305 '!=' 355 ']'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + failure
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + header 'oh no!'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + follow=---------------------------------------------------------
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ echo '---- oh no! ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ head -c 80
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + header='---- oh no! --------------------------------------------------------------------'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo ''
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + _textout '\033[34m' '---- oh no! --------------------------------------------------------------------'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo -en '\033[34m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + shift
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + '[' '---- oh no! --------------------------------------------------------------------' = '' ']'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo '---- oh no! --------------------------------------------------------------------'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ---- oh no! --------------------------------------------------------------------
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo -en '\033[0m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + _textout '\033[31m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo -en '\033[31m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + shift
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + '[' '' = '' ']'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + cat
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: It seems the build user _nixbld5 already exists, but with the UID
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: with the UID '305'. This script can't really handle that right
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: now, so I'm going to give up.
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: If you already created the users and you know they start from
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: 305 and go up from there, you can edit this script and change
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: NIX_FIRST_BUILD_UID near the top of the file to 305 and try
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: again.
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo -en '\033[0m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo ''
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ get_help
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ echo 'We'\''d love to help if you need it.'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ echo ''
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ contact_us
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ echo 'You can open an issue at'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ echo 'https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ echo ''
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: ++ echo 'Or get in touch with the community: https://nixos.org/community'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + _textout '\033[31m' 'We'\''d love to help if you need it.
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: You can open an issue at
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: Or get in touch with the community: https://nixos.org/community'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo -en '\033[31m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + shift
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + '[' 'We'\''d love to help if you need it.
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: You can open an issue at
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: Or get in touch with the community: https://nixos.org/community' = '' ']'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo 'We'\''d love to help if you need it.
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: You can open an issue at
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: Or get in touch with the community: https://nixos.org/community'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: We'd love to help if you need it.
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: You can open an issue at
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: Or get in touch with the community: https://nixos.org/community
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + echo -en '\033[0m'
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + trap finish_cleanup EXIT
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + exit 1
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + finish_cleanup
2024-11-12 15:25:57+01 springfield package_script_service[21020]: ./postinstall: + rm -rf /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.YhNY0z2BMi
2024-11-12 15:25:57+01 springfield package_script_service[21020]: PackageKit: Hosted team responsible for script has been cleared.
2024-11-12 15:25:57+01 springfield package_script_service[21020]: Responsibility set back to self.
2024-11-12 15:25:57+01 springfield install_monitor[38572]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: releasing backupd
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: allow user idle system sleep
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "Beim Ausführen der Skripts aus dem Paket „flox-1.3.3.aarch64-darwin.pkg“ ist ein Fehler aufgetreten." UserInfo={NSFilePath=./postinstall, NSURL=file:///opt/homebrew/Caskroom/flox/1.3.3/flox-1.3.3.aarch64-darwin.pkg#flox-1.3.3.pkg, PKInstallPackageIdentifier=com.floxdev.flox, NSLocalizedDescription=Beim Ausführen der Skripts aus dem Paket „flox-1.3.3.aarch64-darwin.pkg“ ist ein Fehler aufgetreten.} {
            NSFilePath = "./postinstall";
            NSLocalizedDescription = "Beim Ausf\U00fchren der Skripts aus dem Paket \U201eflox-1.3.3.aarch64-darwin.pkg\U201c ist ein Fehler aufgetreten.";
            NSURL = "file:///opt/homebrew/Caskroom/flox/1.3.3/flox-1.3.3.aarch64-darwin.pkg#flox-1.3.3.pkg";
            PKInstallPackageIdentifier = "com.floxdev.flox";
        }
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: Cleared responsibility for install from 38571.
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: Hosted team responsible for install has been cleared.
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: Running idle tasks
2024-11-12 15:25:58+01 springfield installer[38571]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "Beim Ausführen der Skripts aus dem Paket „flox-1.3.3.aarch64-darwin.pkg“ ist ein Fehler aufgetreten." UserInfo={NSFilePath=./postinstall, NSURL=file:///opt/homebrew/Caskroom/flox/1.3.3/flox-1.3.3.aarch64-darwin.pkg#flox-1.3.3.pkg, PKInstallPackageIdentifier=com.floxdev.flox, NSLocalizedDescription=Beim Ausführen der Skripts aus dem Paket „flox-1.3.3.aarch64-darwin.pkg“ ist ein Fehler aufgetreten.}
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: Removing client PKInstallDaemonClient pid=38571, uid=0 (/usr/sbin/installer)
2024-11-12 15:25:58+01 springfield installd[996]: PackageKit: Done with sandbox removals
2024-11-12 15:25:59+01 springfield installer[38571]: Install failed: Die Installation ist aufgrund eines Fehlers fehlgeschlagen. Wende dich an den Hersteller der Software.
```

**Comment by mkenigs** [comment] 2024-11-22 21:26
This error looks like one that I would expect if you happen to have installed Flox (or Nix) installed, upgraded to macOS Sequoia from a prior macOS version, and then tried to install Flox. Is that what happened?

**Comment by osteinhauer** [comment] 2024-11-22 21:27
you're right

**Comment by mkenigs** [comment] 2024-11-22 21:33
Okay thanks! We have some migration logic for that case but maybe we need to make it a bit more exhaustive. If you need a workaround to get you out of the broken state, you should be able to run the uninstallation script (`sudo /usr/local/share/flox/scripts/uninstall`) and then re-install

**Comment by osteinhauer** [comment] 2024-11-22 21:38
🍺  flox was successfully installed!

thx!

**Comment by mkenigs** [comment] 2024-11-22 21:39
> 🍺 flox was successfully installed!
> 
> thx!

🎉🎉🎉
Sorry to be slow getting back to you but glad it's working now!

**Comment by mkenigs** [comment] 2024-11-25 22:54
I couldn't reproduce by installing Flox 1.2.3 on Sonoma, upgrading to Sequoia, and then installing Flox 1.3.5. So I'll close this for now

The only case I'm aware of that might trigger this failure is if there's a partial Nix uninstall on Sonoma that removes `/nix` but not `_nixbld` users , there's an upgrade to Sequoia, , and then there's a Flox install

**Closed by mkenigs** 2024-11-25 22:54 UTC
Labels: bug, team-cli, user-reported
