### ISSUE TITLE
[mkEnv/activate]: tests: Ensure Python3 `requests` flow works

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#405] opened 2023-11-07 14:32 UTC
Create a test harness which ensures `flox install` + `flox activate` _just work_ for a common Python3 + `pip` workflow.

Model your test on the following:
```console
$ flox install python3Packages.pip python3;
$ flox activate;
$ pip install requests && python3;
$ python3;
# Use requests somehow in the test case
```

You may need to add additional dependencies, the script above is a rough sketch.

Use existing Python3 setup script found here : https://github.com/flox/etc-profiles/blob/main/profile.d/0500_python3.sh

Related Node.js ticket: https://github.com/flox/flox/issues/347
Related _product_ ticket: https://github.com/flox/flox/issues/349

## Acceptance Criteria
- [ ] Create a test harness which uses `flox` to install `python3` and `pip`, then uses `pip install` for `requests`.
- [ ] Fix any activation/`mkEnv` issues necessary for the flow to work.

You may find the need to create additional follow up tickets if you discover major issues.
However, 5 points is intended to be enough for a bit of debugging past the creation of the test case.
**Do not** simply create a test case and close this ticket.

**Comment by mkenigs** [comment] 2023-11-07 15:55
> Related Node.js ticket: #347 

Do you mean https://github.com/flox/flox/issues/404?

**Comment by aakropotkin** [comment] 2023-11-08 01:15
> > Related Node.js ticket: #347
> 
> Do you mean #404?

Yes

**Comment by samrose** [comment] 2023-11-08 17:50
@aakropotkin changing acceptance criteria description to `flox install python3Packages.pip` as this is what flox currently supports. If any issue just let me know

**Comment by mkenigs** [comment] 2023-11-08 17:51
I think with recent changes plain `pip` should work

**Comment by samrose** [comment] 2023-11-08 17:52
@mkenigs it doesn't

**Comment by samrose** [comment] 2023-11-08 17:52
```
flox install pip
warning: input 'flox-floxpkgs/etc-profiles' has an override for a non-existent input 'flox-floxpkgs'
error:
       … while calling the 'head' builtin

         at /nix/store/ma9ipxi95nzimpfaflr9hyjfq46jnrcg-source/lib/attrsets.nix:820:11:

          819|         || pred here (elemAt values 1) (head values) then
          820|           head values
             |           ^
          821|         else

       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Channel nixpkgs-flox does not contain evalCatalog.x86_64-linux.stable.pip or packages.x86_64-linux.pip or legacyPackages.x86_64-linux.pip

ERROR: failed to install packages: flake:nixpkgs-flox#evalCatalog.x86_64-linux.stable.pip
```

**Comment by samrose** [comment] 2023-11-08 17:53
sam@samrose-flox:~/flox-pip$ flox --version
Version: 0.3.5-r660

**Comment by mkenigs** [comment] 2023-11-08 17:57
It works with `0.3.7-r733` built from main:
```
./target/debug/flox init --dir ~/debug && ./target/debug/flox install pip --dir ~/debug && SHELL=bash ./target/debug/flox activate --dir ~/debug
✨ created environment debug (aarch64-darwin)

Enter the environment with "flox activate"
Search and install packages with "flox search {packagename}" and "flox install {packagename}"

✅ 'pip' installed to environment debug at /Users/matthew/debug/.flox
Building environment...
\[\]\[\]flox \[\][debug]\[\] Matthews-MacBook-Pro-2:main matthew$ which pip
/Users/matthew/debug/.flox/run/aarch64-darwin.debug/bin/pip
```

**Comment by samrose** [comment] 2023-11-08 20:12
Exploring 


pip does have a simple option to provide a  --target option like pip install --target=$PWD requests  this worked with flox


\[\]\[\]flox \[\][debug]\[\] bash-5.2$ pip install --target=$PWD requests
Collecting requests
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/da/f1/3702ba2a7470666a62fd81c58a4c40be00670e5006a67f4d626e57f013ae/charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/d2/b2/b157855192a68541a91ba7b2bbcb91f1b4faa51f8bae38d8005c034be524/urllib3-2.0.7-py3-none-any.whl.metadata
  Downloading urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.4 MB/s eta 0:00:00
Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 12.7 MB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 kB 19.5 MB/s eta 0:00:00
Downloading urllib3-2.0.7-py3-none-any.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 34.9 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2023.7.22 charset-normalizer-3.3.2 idna-3.4 requests-2.31.0 urllib3-2.0.7
\[\]\[\]flox \[\][debug]\[\] bash-5.2$ python3
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 

and there is a pip.ini config https://pip.pypa.io/en/stable/topics/configuration/

Moreover, there is a PIP_CONFIG_FILE env var that gets read first, that we could set with a default, and also make overridable as part of the core flox env, and this theoretically will create a default that still puts deps on the path in a nix env shell, and should be reproducible if we do it right. I am not the deepest of experts on this, but so far this seems to be the direction.  We are discusing it internally see what folks think before digging further in this direction

**Comment by samrose** [comment] 2023-11-09 20:20
...update we decided to move forward with the PIP_CONFIG_FILE approach per environment.

**Comment by garbas** [comment] 2023-11-17 16:30
I've done some digging and here how I came to understand this python packaging world.

- `pip install` will install relative to python executable. In Nix's case this means somewhere in `/nix/store` which is read only (obviously). This is the output you get when you try to install something with pip in flox environment:
   
```
flox [flox] bash-5.2$ pip install test
error: externally-managed-environment

× This environment is externally managed
╰─> This command has been disabled as it tries to modify the immutable
    `/nix/store` filesystem.

    To use Python with Nix and nixpkgs, have a look at the online documentation:
    <https://nixos.org/manual/nixpkgs/stable/#python>.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

- python in Nix is marked as *externally managed* (as per [PEP-668](https://peps.python.org/pep-0668/). There is even a [custom error message provided by Nix](https://github.com/NixOS/nixpkgs/blob/e4df5bf73601b3fc27bc829443ece91d5b15a506/pkgs/development/interpreters/python/cpython/default.nix#L526-L533) when `pip install` tries to be used.

- Using `--target` from distance looks like it could be the solution, but once you go down that rabbit whole you realize that the `--target` option is a minefield. For those interested in details you read [an issue opened in 2020](https://github.com/pypa/pip/issues/8063).

So what to do? What would be the "correct" way.

If you follow the official documentation on [how to install python packages](https://packaging.python.org/en/latest/tutorials/installing-packages/) it is obvious you should use virtualenv. That was the case when I was actively using python and I guess still is the correct way to install packages. The good thing is virtual environments is now a builtin feature: `python -m venv ./path/to/env`.

My suggestion is: **We configure pip to tell users to use virtualenv**.

We can do this by using `PIP_CONFIG_FILE` and set `require-virtualenv = true` and then we would get:

```
flox [flox] bash-5.2$ pip install test
ERROR: Could not find an activated virtualenv (required).
```

I think this would be the best we could do right now, but we still have option to automatically create virtualenv for you and add it to path, but that path would need some more investigation if this is really what users would expect.

**Comment by samrose** [comment] 2023-11-17 16:42
> Using --target from distance looks like it could be the solution, but once you go down that rabbit whole you realize that the --target option is a minefield. For those interested in details you read https://github.com/pypa/pip/issues/8063.


Cool, I am glad you uncovered these issues @garbas  it may be a harder UX outcome to steer people toward virtualenv, but I agree 100% with your recommendation based on what you found looking into this. 

We could both explore using virtualenv, plus explore how to make it easier to use it, and explain to our users why we had to double down on virtualenv recommendation/direction in our docs. While it is true that there are some people who do not use virtualenv, most people who use pip probably do use virtualenv for their own sanity.

**Comment by garbas** [comment] 2023-11-22 07:57
This has now been done in https://github.com/flox/flox/issues/405

**Closed by garbas** 2023-11-22 07:57 UTC
Labels: tests, product
