### ISSUE TITLE
Auto exit/activate on "flox activate" inside an activated repo?

### ISSUE THREAD

**Issue by aronchick** [flox/flox#1655] opened 2024-06-18 22:37 UTC
Just a nicety.

```
❯ flox edit
⚠️  Your manifest has changes that cannot be automatically applied.

Please 'exit' the environment and run 'flox activate' to see these changes.

❯ flox activate
❌ ERROR: Environment 'aronchick/bacalhau' is already active.
❯ exit
❯ flox activate
✅ You are now using the environment 'aronchick/bacalhau'.
To stop using this environment, type 'exit'

Beginning activation of Flox environment
Activating python virtual environment
Setting up Go environment
```

**Comment by ghudgins** [comment] 2024-06-18 22:51
looks like a duplicate of https://github.com/flox/flox/issues/1415

**Comment by ghudgins** [comment] 2024-07-24 14:47
closing as duplicate

**Closed by ghudgins** 2024-07-24 14:47 UTC
Labels: enhancement, team-cli
