### ISSUE TITLE
flox 1.3.3 install fails (and uninstall is unable to unmount nix store)

### ISSUE THREAD

**Issue by jaydeland** [flox/flox#2178] opened 2024-10-02 18:31 UTC
**Describe the bug:**
Error when trying to upgrade flox via brew resulted in flox being removed from my system and now trying to install fails.

**Steps to reproduce:**
1. `brew install flox`
2. Enter pwd for sudo access
3. Fails
4. I also than attempted to install with the pkg (screenshot attached)

Result:
```sh
❯ brew install flox --verbose
==> Downloading https://downloads.flox.dev/by-env/stable/osx/flox-1.3.3.aarch64-darwin.pkg
Already downloaded: /Users/jdeland/Library/Caches/Homebrew/downloads/4559bc557260a2ee6bb8c11efec639023690b13beaf6a5653ae1503a0c6791a1--flox-1.3.3.aarch64-darwin.pkg
==> Verifying checksum for '4559bc557260a2ee6bb8c11efec639023690b13beaf6a5653ae1503a0c6791a1--flox-1.3.3.aarch64-darwin.pkg'
==> Installing Cask flox
cp -p /Users/jdeland/Library/Caches/Homebrew/downloads/4559bc557260a2ee6bb8c11efec639023690b13beaf6a5653ae1503a0c6791a1--flox-1.3.3.aarch64-darwin.pkg /opt/homebrew/Caskroom/flox/1.3.3/flox-1.3.3.aarch64-darwin.pkg
==> Running installer for flox with sudo; the password may be necessary.
Password:
installer: Package name is Flox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Flox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%49.807766
installer:PHASE:Running package scripts…
installer:%51.307642
installer:PHASE:Running package scripts…
installer:%52.611848
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “flox-1.3.3.aarch64-darwin.pkg”.)
==> Purging files for version 1.3.3 of Cask flox
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=jdeland USER=jdeland USERNAME=jdeland -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/flox/1.3.3/flox-1.3.3.aarch64-darwin.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Flox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Flox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%49.807766
installer:PHASE:Running package scripts…
installer:%51.307642
installer:PHASE:Running package scripts…
installer:%52.611848
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “flox-1.3.3.aarch64-darwin.pkg”.)
```
Expected:

**Screenshots/terminal output (if relevant):**
![Image](https://github.com/user-attachments/assets/d4e7a587-4d06-4acb-9914-a8952328dba6)

**Flox Version (run `flox --version` if possible):**

**`uname -a` output:**
`Darwin Jasons-MacBook-Air.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64`

**Comment by ghudgins** [comment] 2024-10-02 19:36
taking a look right away

**Comment by ghudgins** [comment] 2024-10-02 19:57
can you try doing a full uninstall with `brew uninstall --force --zap flox` and then installing fresh? does that work?

**Comment by jaydeland** [comment] 2024-10-02 20:24
Here is the output:
```sh
❯ brew uninstall --force --zap flox
==> Implied `brew uninstall --cask flox`
==> Removing launchctl service org.nixos.darwin-store
Password:
==> Removing launchctl service org.nixos.nix-daemon
==> Running uninstall script /usr/local/share/flox/scripts/uninstall
Warning: uninstall script /usr/local/share/flox/scripts/uninstall does not exist; skipping.
==> Uninstalling packages with sudo; the password may be necessary:
==> Dispatching zap stanza
==> Running uninstall script /usr/local/share/flox/scripts/uninstall_zap
   7:                APFS Volume Nix Store               15.5 GB    disk3s7
Volume Nix Store on disk3s7 failed to unmount
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
Could not unmount /nix; make sure no processes using Nix or Flox are running, and then re-run this uninstaller.
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/local/share/flox/scripts/uninstall_zap --zap` exited with 1. Here's the output:
   7:                APFS Volume Nix Store               15.5 GB    disk3s7
Volume Nix Store on disk3s7 failed to unmount
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
Could not unmount /nix; make sure no processes using Nix or Flox are running, and then re-run this uninstaller.
```

**Comment by jaydeland** [comment] 2024-10-02 20:36
I had to manually unmount the /nix mount and then it worked.
```sh
❯ diskutil unmountDisk /dev/disk3s7
Unmount of disk3 failed: at least one volume could not be unmounted
Unmount was dissented by PID 1 (/sbin/launchd)
Dissenter parent PPID 0 (kernel_task)
❯ sudo diskutil unmount force /dev/disk3s7
Password:
disk3s7 was already unmounted
```

**Comment by stahnma** [comment] 2024-10-08 15:35
@bryanhonof Ping since you asked

**Comment by ghudgins** [comment] 2024-10-08 15:35
solution idea: `flox doctor` or something to do common reset actions?

**Comment by tomberek** [comment] 2024-10-11 15:28
I'm still not sure what the original error was caused by. Do we have a copy of the `/var/log/install.log`?

**Comment by stahnma** [comment] 2024-10-22 15:32
We haven't been able to reproduce this. Our suggested path forward is to update our docs to encourage the usage of `--zap` as a cleanall mechanism to get back to a pristine state.

**Comment by tomberek** [comment] 2024-10-22 16:02
Not able to reproduce, closing for now. Re-open if we have more information or we have more reports. Adding an issue to provide some of the recovery mechanism in docs.

**Closed by tomberek** 2024-10-22 16:02 UTC
Labels: bug, team-developer-support
